version: '3'

services:
  products:
    image: postgres
    container_name: products
    environment:
      POSTGRES_PASSWORD: product
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    

  orders:
    image: postgres
    container_name: orders
    environment:
      POSTGRES_PASSWORD: order
      POSTGRES_DB: orders
    ports:
      - "5431:5432"
   

  validation:
    image: postgres
    container_name: validation
    environment:
      POSTGRES_PASSWORD: valid
      POSTGRES_DB: validation
    ports:
      - "5433:5432"
    

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  ordermanager_messaging:
    image: wurstmeister/kafka
    container_name: ordermanager_messaging
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ordermanager_messaging:9092
    command: "start-kafka.sh"

  asw-consul:
    image: docker.io/hashicorp/consul
    container_name: asw-consul
    ports:
      - "8500:8500"

  order-service:
    image: ordermanager-order
    deploy:
      replicas: 2

  product-service:
    image: ordermanager-product
    deploy:
      replicas: 2

  ordervalidation-service:
    image: ordermanager-validation
    deploy:
      replicas: 2

  api-gateway1:
    image: ordermanager-api-gateway
    container_name: api-gateway1
    ports:
      - "8080:8080"

  api-gateway2:
    image: ordermanager-api-gateway
    container_name: api-gateway2
    ports:
      - "8081:8081"

  
    
    

